# Use postgres/example user/password credentials
version: '3.1'

services:
  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    environment:
      - MONGODB_USERNAME=mongo-user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=DocumentOrganizer
    ports:
      - 27017:27017
  