# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: products
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    image: homedocumentorganizer_web
    ports:
      - 3000:3000
    depends_on: 
      - db
    environment:
      POSTGRES_URI: postgres://postgres:pa55word@db:5432/products
  